# Gradle Properties
	org.gradle.jvmargs=-Xmx4G

# Fabric Basic Properties
	# https://fallen-breath.github.io/fabric-versions/
	loader_version=0.19.3

# Mod Properties
	mod_id = safeafk-auto-off
	mod_name = SafeAFK Auto Off
	mod_version = 1.0.0
	maven_group = com.example
	archives_base_name = safeafk-auto-off

# Global Dependencies
	# https://github.com/Fallen-Breath/conditional-mixin
	conditionalmixin_version = 0.6.4

	# https://github.com/LlamaLad7/MixinExtras
	mixinextras_version = 0.3.6
